// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package appbase

import "fmt"

func (setting *Setting) Int8List(defaultValue []int8) (target *[]int8) {
	setting.application.viper.SetDefault(setting.viperPath, defaultValue)

	var realFinalValue []int8
	target = &realFinalValue

	setting.kingpinFlag.Default(fmt.Sprint(defaultValue)).Int8List()
	setting.readIn = func() (err error) {
		err = setting.application.viper.UnmarshalKey(setting.viperPath, target)
		return
	}
	return
}
