// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package appbase

import "fmt"

func (setting *Setting) BoolList(defaultValue []bool) (target *[]bool) {
	setting.application.viper.SetDefault(setting.viperPath, defaultValue)

	var realFinalValue []bool
	target = &realFinalValue

	setting.kingpinFlag.Default(fmt.Sprint(defaultValue)).BoolList()
	setting.readIn = func() (err error) {
		err = setting.application.viper.UnmarshalKey(setting.viperPath, target)
		return
	}
	return
}
